import { z } from 'zod';

/** Every entity id is a UUIDv7 generated by the server. */
export const Id = z.uuid();

/** Timestamps travel as ISO-8601 strings with an offset. */
export const Timestamp = z.iso.datetime({ offset: true });

export const Slug = z
  .string()
  .min(2)
  .max(48)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'Use lowercase letters, numbers and single dashes');

/** Cursor pagination: the cursor is opaque to clients. */
export const PageQuery = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().max(200).optional(),
});
export type PageQuery = z.infer<typeof PageQuery>;

export const PageInfo = z.object({
  nextCursor: z.string().nullable(),
});

export function pageOf<T extends z.ZodType>(item: T) {
  return z.object({ data: z.array(item), page: PageInfo });
}

export type Page<T> = { data: T[]; page: { nextCursor: string | null } };

/** RFC 9457 problem details, extended with a stable machine-readable code. */
export const ProblemDetails = z.object({
  type: z.string(),
  title: z.string(),
  status: z.number().int(),
  code: z.string(),
  detail: z.string().optional(),
  instance: z.string().optional(),
  requestId: z.string().optional(),
  errors: z.array(z.object({ path: z.string(), message: z.string() })).optional(),
});
export type ProblemDetails = z.infer<typeof ProblemDetails>;

export const ROLES = ['owner', 'admin', 'member', 'viewer'] as const;
export const Role = z.enum(ROLES);
export type Role = z.infer<typeof Role>;

export const OkResponse = z.object({ ok: z.literal(true) });
