import { customType, timestamp, uuid } from 'drizzle-orm/pg-core';

/** timestamptz everywhere; the application works in UTC Date objects. */
export const ts = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

export const createdAt = () => ts('created_at').notNull().defaultNow();
export const updatedAt = () => ts('updated_at').notNull().defaultNow();

/** Primary keys are UUIDv7 values generated by the application (see shared-kernel/ids.ts). */
export const idColumn = () => uuid('id').primaryKey();

/** Postgres full-text search document. Drizzle has no built-in tsvector type. */
export const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return 'tsvector';
  },
});

/** Renders a SQL list of string literals for CHECK constraints: ('a', 'b'). */
export const sqlList = (values: readonly string[]) =>
  `(${values.map((v) => `'${v.replace(/'/g, "''")}'`).join(', ')})`;
