import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import { eq } from 'drizzle-orm';
import { blobs } from '../../../db/schema';
import type { Database } from '../../../platform/database/client';
import type { BlobStorage } from '../application/ports';

const KEY_PATTERN = /^[a-z0-9][a-z0-9/_-]{0,255}$/i;

function assertKey(key: string): void {
  if (!KEY_PATTERN.test(key) || key.includes('..')) throw new Error(`Invalid blob key: ${key}`);
}

/** Local disk. Keys are generated by the server (never user filenames) and resolved under the base dir. */
export class FilesystemBlobStorage implements BlobStorage {
  readonly kind = 'filesystem';
  private readonly base: string;

  constructor(baseDir: string) {
    this.base = resolve(baseDir);
  }

  private pathFor(key: string): string {
    assertKey(key);
    const path = resolve(this.base, key);
    if (!path.startsWith(this.base + sep))
      throw new Error('Blob key escapes the storage directory');
    return path;
  }

  async put(key: string, bytes: Uint8Array): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);
  }

  async get(key: string): Promise<Uint8Array | null> {
    try {
      return new Uint8Array(await readFile(this.pathFor(key)));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }
}

/** Bytes in a Postgres table: durable on hosts with an ephemeral disk; fine for documents up to 10 MB. */
export class PostgresBlobStorage implements BlobStorage {
  readonly kind = 'postgres';

  constructor(private readonly db: Database) {}

  async put(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
    assertKey(key);
    await this.db
      .insert(blobs)
      .values({ key, contentType, sizeBytes: bytes.length, content: Buffer.from(bytes) })
      .onConflictDoNothing();
  }

  async get(key: string): Promise<Uint8Array | null> {
    const [row] = await this.db
      .select({ content: blobs.content })
      .from(blobs)
      .where(eq(blobs.key, key))
      .limit(1);
    return row ? new Uint8Array(row.content) : null;
  }

  async delete(key: string): Promise<void> {
    await this.db.delete(blobs).where(eq(blobs.key, key));
  }
}
